config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get '/auth/:provider/callback' => 'sessions#create'
  delete '/sessions/:id' => 'sessions#destroy'

  resources :users do
    resources :favorites
  end

  resources :recipes do
    resources :ratings
  end

  resources :sessions, :favorites, :ratings, :ingredients, :recipes
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
  validates :recipe, uniqueness: { scope: :user_id }
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorites.all
    respond_to do |format|
      format.html
      format.json { render json: @favorites }
    end
  end

  def create
    @favorite = Favorite.new(favorite_params)
    if @favorite.save
      redirect_to user_favorites_path(current_user)
    else
      flash[:message] = 'Already Favorited!'
      redirect_to :back
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.delete
    redirect_to user_path(current_user)
  end

  private

  def favorite_params
    params.require(:favorite).permit(:recipe_id, :user_id)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/index.html.erb
<div id="favorites_index" class="ui raised text container segment">
  <h1 class="ui centered header"><%= "#{ current_user.name }'s Favorite Recipes" %></h1>
</div>

<div class="ui raised text container segment">
  <div id="js-favorite_recipe" class="ui middle aligned selection list">
    <% @favorites.each do |favorite| %>
      <div class="item js-title">
        | <%= link_to "Remove", favorite_path(favorite), :method => "delete" %>
      </div>
    <% end %>
  </div>
</div>