config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get '/auth/:provider/callback' => 'sessions#create'
  delete '/sessions/:id' => 'sessions#destroy'

  resources :users do
    resources :favorites
  end

  resources :recipes do
    resources :ratings
  end

  resources :sessions, :favorites, :ratings, :ingredients, :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients, dependent: :destroy
  has_many :favorites
  has_many :ratings
  validates :title, :description, :directions, presence: true

  # Strip neccassary white space
  auto_strip_attributes :title, :description, :directions, :prep_time, :cook_time, :squish => true

  def ingredients_attributes=(ingredients_attributes)
    ingredients_attributes.each do |i, attr|
      unless attr[:name].blank?
        ingredient = Ingredient.find_or_create_by(:name => attr[:name])

        if self.recipe_ingredients.ids.empty?
          self.recipe_ingredients.build(ingredient: ingredient, quantity: attr[:quantity])

        else
          self.recipe_ingredients[i.to_i].update(ingredient: ingredient, quantity: attr[:quantity])
        end
      end
    end
  end

  def self.recipes_of_the_day
    self.order("Random()").limit(5)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :require_login, only: %i[new create]
  def index
    if params[:search]
      @recipes = Recipe.where('title LIKE ?', '%#{params[:search]}%')
    else
      @recipes = Recipe.all
      respond_to do |format|
        format.html
        format.json { render json: @recipes }
      end
    end
  end

  def new
    @recipe = Recipe.new
    @ingredient = @recipe.ingredients.build
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      flash[:error] = @recipe.errors.full_messages.join(', ')
      redirect_back(fallback_location: new_recipe_path)
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @ratings = @recipe.ratings.all
    @favorite = Favorite.new
    @rating = Rating.new
    respond_to do |format|
      format.html
      format.json { render json: @recipe }
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)
    redirect_to recipe_path(@recipe)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description, :directions,
                                   :prep_time, :cook_time, :gluten_free, :vegan,
                                   ingredients_attributes: %i[id quantity name])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def if_logged_in_options
    if !logged_in?
      link_to 'Login to Create Review', new_session_path, class: 'ui right floated button'
    elsif current_user != @recipe.user.id
      link_to 'Write Review', new_recipe_rating_path(@recipe), class: 'ui right floated button'
    end
  end
end

app/views/recipes/_recipe_form.html.erb
<div class="required fluid field">
    <%= f.label :title %>
    <%= f.text_field :title, :placeholder => "Spider Goulash"  %><br><br>
</div>
<div class="required fluid field">
    <%= f.label :description %>
    <%= f.text_area :description %><br><br>
</div>
<div class="fluid field">
    <%= f.label :prep_time %>
    <%= f.text_field :prep_time %><br><br>
</div>
<div class="fluid field">
    <%= f.label :cook_time %>
    <%= f.text_field :cook_time, :placeholder => "20 mins" %><br><br>
</div>
<div class="required fluid field">
    <%= f.label :directions %>
    <%= f.text_area :directions %><br><br>
</div>
<div class="inline fields">
    <%= f.label :vegan %>
    <%= f.check_box :vegan %>

    <%= f.label :gluten_free %>
    <%= f.check_box :gluten_free %>
</div>

<div class="field required">
  <%= label_tag "Ingredients" %>
</div>

app/views/recipes/edit.html.erb
<%= form_for @recipe, :html => { :class => "ui form" } do |f| %>
  <div class="ui raised text container segment">

    <%= render 'recipe_form', f: f %>

      <%= f.fields_for :ingredients do |i| %>
          <div class="fluid field">
            <%= i.label :quantity %>
            <input type="text" name="recipe[ingredients_attributes][<%= i.index %>][quantity]"
              value="<%= @recipe.recipe_ingredients[ i.index ].quantity %>" /><br>

            <%= i.label "Ingredient #{ i.index + 1 }" %>
            <%= i.text_field :name %>
          </div>
      <% end %>

      <%= f.submit 'Edit Recipe', :class => "ui teal huge submit button fluid" %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<%= form_tag(recipes_path, :method => 'get', :class => "ui form") do %>
<div class="ui rased text container segment">
  <div class="fluid field">
    <%= label_tag :search %>
    <%= text_field_tag :search, params[:search], :placeholder => "Search in Recipes" %>
  </div>
    <%= submit_tag "Search Recipes", :class => "ui teal huge submit button fluid" %>
  <% end %>
</div>

<div class="ui raised text container segment">
  <div class="ui list">
    <h1 class="ui centered header"><%= link_to "Create New Recipe", new_recipe_path %></h1>
    <!-- <%# @recipes.each do |recipe| %>
      <h1 class="ui centered header"><%#= link_to recipe.title, recipe_path(recipe) %> | <%#= recipe.user.name %></h1>
    <%# end %> -->
  </div>
</div>

app/views/recipes/new.html.erb
<%= form_for @recipe, :html => { :class => "ui form" } do |f| %>
  <div id="parent_add_ingredient" class="ui raised text container segment">
    <%= render 'users/form_errors', object: @recipe %>

    <%= render 'recipe_form', f: f %>

    <% 1.times do |n| %>
      <%= f.fields_for :ingredients do |i| %>
        <div class="fluid field">
          <%= i.label :quantity %>
          <input type="text" name="recipe[ingredients_attributes][<%= n %>][quantity]" /><br>
          <%= i.label "Ingredient #{ n + 1 }" %>
          <%= i.text_field :name %>
        </div><br>
      <% end %>
    <% end %>

  </div>
  <div class="ui text container">
    <button id="add_ingredient" type="button" class="ui teal huge button">Add Ingredient</button><br><br>

      <%= f.submit 'Create Recipe', :class => "ui teal huge submit button fluid text container" %>
  </div>
<% end %>

app/views/recipes/show.html.erb
<div id="show_recipe_details" class="ui raised text container segment">

  <% if logged_in? && current_user != @recipe.user %>
    <%= form_for @favorite do |f| %>
    <%= f.hidden_field :recipe_id, :value => @recipe.id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.submit 'Add Recipe to Favorites', { :class => 'ui left floated button' } %>
    <% end %>
  <% end %>

  <%= if_logged_in_options %>

  <h1 id="recipe_title" class="ui centered header"></h1>
  <h1 id="recipe_description" class="ui centered header">Description: </h1>
  <h1 id="recipe_prep_time" class="ui centered header">Prep Time: </h1>
  <h1 id="recipe_cook_time" class="ui centered header">Cook Time: </h1>
  <h1 id="recipe_directions" class="ui centered header">Directions: </h1>

  <div id="recipe_ingredients" class="ui list">
    <h1 id="total_amount" class="ui centered header">Total Number of Ingredients: </h1>
    <h1 class="ui centered header">Ingredients: </h1>
  </div>

  <h1 class="ui centered header">Vegan: <i id="checkmark" class="ui centered remove icon"></i></h1>
  <h1 class="ui centered header">Gluten Free: <i id="remove" class="ui centered remove icon"></i></h1>
</div>

<div class="ui raised text container segment">
  <h1 class="ui centered header"><%= link_to "Show Reviews", recipe_ratings_path(@recipe.id), id: "js-show_review" %></h1>
  <div class="ui very padded segment show_hide">
    <h1 class="ui centered header"><span id="user"></span>'s Review</h1>
    <h1 class="ui centered header">Rating: <span id="rating"></span></h1>
    <h1 class="ui centered header">Review: </h1>
    <h1 id="review" class="ui centered header"></h1>
    <a href="#"><i id="previous_rating" class="arrow left icon large"></i></a>
    <a href="#"><i id="next_rating" class="arrow right icon large"></i></a>
  </div>
</div>

<div id="hidden_recipe_field" class="ui raised text container segment">
  <%= form_for @rating, :html => { :class => "ui form" } do |f| %>

    <%= render 'users/form_errors', object: @rating %>

      <div class="required fluid field">
        <%= f.label :rating %>
        <%= f.number_field :rating, :placeholder => '0 - 5' %>
      </div>
      <div class="required fluid field">
        <%= f.label :review %>
        <%= f.text_area :review %>
      </div>
      <%= f.hidden_field :recipe_id, :value => @recipe.id %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.submit 'Submit Review', :class => 'ui teal huge submit button fluid' %>
  <% end %>
</div>