config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get '/auth/:provider/callback' => 'sessions#create'
  delete '/sessions/:id' => 'sessions#destroy'

  resources :users do
    resources :favorites
  end

  resources :recipes do
    resources :ratings
  end

  resources :sessions, :favorites, :ratings, :ingredients, :recipes
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :recipes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :ratings, dependent: :destroy

  validates :password, confirmation: true
  validates :name, :email, presence: true
  validates :email, uniqueness: true

  # Create User with auth value from Twitter or Facebook
  def self.sign_in_with_auth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth['info']['name']
      user.email = auth['info']['email']
      user.password = SecureRandom.hex
      user.save!
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid? && @user.save
      session[:id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    current_user
    @recipes = current_user.recipes.all
  end

  def edit
    @user = current_user
  end

  def destroy
    current_user.destroy && reset_session
    redirect_to new_user_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :provider, :uid, :name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= render 'form_errors', object: @user %>
<div class="ui raised text container segment">
<div class="required fluid field">
  <%= f.label :name %>
  <%= f.text_field :name, :placeholder => "Name" %><br><br>
</div>
<div class="required fluid field">
  <%= f.label :email %>
  <%= f.email_field :email, :placeholder => "example@gmail.com" %><br><br>
</div>
<div class="required fluid field">
  <%= f.label :password %>
  <%= f.password_field :password, :placeholder => "*****" %><br><br>
</div>
<div class="required fluid field">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, :placeholder => "*****" %><br><br>
</div>

app/views/users/_form_errors.html.erb
<% if object.errors.any? %>
<div class="ui red message">
  <h2><%= pluralize(object.errors.count, "error") %>
    prohibited this from being saved:</h2>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user, :html => { :class => "ui form" } do |f| %>

<%= render 'form', f: f %>

<% end %>

app/views/users/new.html.erb
<%= render 'sessions/icon_sign_in' %>

<h1 class="ui centered header">Please sign up</h1>
<%= form_for @user, :html => { :class => "ui form" } do |f| %>

  <%= render 'form', f: f %>

    <%= f.submit 'Create User', :class => "ui teal huge submit button fluid" %>
</div>
<% end %>
<div class="ui raised text container segment">
  <h1 class="ui centered header">If already a user please <%= link_to "sign in!", new_session_path %></h1>
</div>

app/views/users/show.html.erb
<%= which_layout %>
<div class="ui raised text container segment">
  <h1 class="ui centered header">Welcome <%= "#{current_user.name}!" %></h1>
  <h1 class="ui centered header"><%= link_to "Delete User", user_path(current_user), :method => "delete" %></h1>

</div>
<div class="ui raised text container segment">
  <h1 class="ui centered header"><%= link_to "Create New Recipe", new_recipe_path %></h1>
  <h1 class="ui centered header"><%= link_to "Favorite Recipes", user_favorites_path(current_user) %></h1>
  <div class="ui middle aligned selection list">
    <% @recipes.each do |recipe| %>
      <div class="item">
        <%= link_to "#{recipe.title}", recipe_path(recipe) %> |
        <%= link_to "Edit", edit_recipe_path(recipe) %>
      </div>
    <% end %>
  </div>
</div>